baseURL = 'https://ccyang34.github.io/Hugo-blog/'
languageCode = 'zh-cn'
title = '我的 Hugo 博客'
theme = 'clarity'
relativeURLs = true
canonifyURLs = true

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "我的 Hugo 个人博客 - 使用 Clarity 主题并模仿 Anzhiyu 布局"
  author = "ccyang34"
  introDescription = "一个追求极致体验的 Hugo 博客"
  enableSearch = true
  mainSections = ["posts"]
  codeMaxLines = 10
  codeLineNumbers = true
  mobileNavigation = "left"

[menu]
  [[menu.main]]
    name = "首页"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "分类"
    url = "/categories/"
    weight = 2
  [[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "归档"
    url = "/posts/"
    weight = 4

[outputs]
  home = ["HTML", "RSS", "JSON"]
