baseURL = 'https://ccyang34.github.io/Hugo-blog/'
languageCode = 'zh-cn'
title = '我的 Hugo 博客'
theme = 'relearn'
relativeURLs = true
canonifyURLs = true

[outputs]
  home = ["html", "rss", "print", "search"]
  section = ["html", "rss", "print", "search"]
  page = ["html", "rss", "print", "search"]

[params]
  # 可以在这里添加 Relearn 特有的参数
  editURL = ""
  description = "我的 Hugo 个人博客 - 使用 Relearn 主题"
  author = "ccyang34"
  showBreadcrumbs = true
