baseURL = 'https://hugo.ccyang.online/'
languageCode = 'zh-cn'
title = "CCY's Hugo"
theme = 'stack'

DefaultContentLanguage = 'zh-cn'
hasCJKLanguage = true

[pagination]
  pagerSize = 10

[permalinks]
  posts = '/posts/:slug/'

[params]
  mainSections = ['posts']
  featuredImageField = 'image'
  rssFullContent = true

  [params.footer]
    since = 2024

  [params.dateFormat]
    published = '2006å¹´01æœˆ02æ—¥'
    lastUpdated = '2006å¹´01æœˆ02æ—¥ 15:04'

  [params.sidebar]
    emoji = 'ğŸš€'
    subtitle = "CCY's Hugo - ä¸ªäººåšå®¢"
    [params.sidebar.avatar]
      enabled = true
      local = true
      src = 'img/avatar.png'

  [params.article]
    math = false
    toc = true
    readingTime = true
    [params.article.license]
      enabled = false

  [params.comments]
    enabled = false

  [params.widgets]
    [[params.widgets.homepage]]
      type = 'search'
    [[params.widgets.homepage]]
      type = 'archives'
      [params.widgets.homepage.params]
        limit = 5
    [[params.widgets.homepage]]
      type = 'categories'
      [params.widgets.homepage.params]
        limit = 10
    [[params.widgets.homepage]]
      type = 'tag-cloud'
      [params.widgets.homepage.params]
        limit = 15
    [[params.widgets.page]]
      type = 'toc'

  [params.colorScheme]
    toggle = true
    default = 'auto'

  [params.imageProcessing]
    [params.imageProcessing.cover]
      enabled = true
    [params.imageProcessing.content]
      enabled = true

[[menu.social]]
  identifier = 'github'
  name = 'GitHub'
  url = 'https://github.com/ccyang34'
  [menu.social.params]
    icon = 'brand-github'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    endLevel = 4
    ordered = true
    startLevel = 2
  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    lineNos = true
    tabWidth = 4

[outputs]
  home = ['HTML', 'RSS', 'JSON']

[taxonomies]
  category = 'categories'
  tag = 'tags'
