baseURL = 'https://hugo.ccyang.online/'
languageCode = 'zh-cn'
title = "CCY's Hugo"
theme = 'clarity'
relativeURLs = false
canonifyURLs = false

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "CCY's Hugo - 个人博客"
  author = "ccyang34"
  dateFormat = "2006年01月02日 15:04:05"
  introDescription = "一个追求极致体验的 Hugo 博客"
  enableSearch = true
  mainSections = ["posts"]
  codeMaxLines = 10
  codeLineNumbers = true
  mobileNavigation = "left"

[menu]
  [[menu.main]]
    name = "首页"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "分类"
    url = "/categories/"
    weight = 2
  [[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "归档"
    url = "/posts/"
    weight = 4

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
